// Code generated by protoc-gen-go.
// source: searchdata.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	searchdata.proto

It has these top-level messages:
	SearchItem
	SearchResult
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchItem struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	DownloadTimes    *int32  `protobuf:"varint,2,req,name=DownloadTimes" json:"DownloadTimes,omitempty"`
	DownloadSpeed    *string `protobuf:"bytes,3,req,name=DownloadSpeed" json:"DownloadSpeed,omitempty"`
	CollectTime      *string `protobuf:"bytes,4,req,name=CollectTime" json:"CollectTime,omitempty"`
	FileSize         *string `protobuf:"bytes,5,req,name=FileSize" json:"FileSize,omitempty"`
	FileCount        *string `protobuf:"bytes,6,req,name=FileCount" json:"FileCount,omitempty"`
	Popular          *int32  `protobuf:"varint,7,req,name=Popular" json:"Popular,omitempty"`
	MagnetURI        *string `protobuf:"bytes,8,req,name=MagnetURI" json:"MagnetURI,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SearchItem) Reset()                    { *m = SearchItem{} }
func (m *SearchItem) String() string            { return proto.CompactTextString(m) }
func (*SearchItem) ProtoMessage()               {}
func (*SearchItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SearchItem) GetDownloadTimes() int32 {
	if m != nil && m.DownloadTimes != nil {
		return *m.DownloadTimes
	}
	return 0
}

func (m *SearchItem) GetDownloadSpeed() string {
	if m != nil && m.DownloadSpeed != nil {
		return *m.DownloadSpeed
	}
	return ""
}

func (m *SearchItem) GetCollectTime() string {
	if m != nil && m.CollectTime != nil {
		return *m.CollectTime
	}
	return ""
}

func (m *SearchItem) GetFileSize() string {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return ""
}

func (m *SearchItem) GetFileCount() string {
	if m != nil && m.FileCount != nil {
		return *m.FileCount
	}
	return ""
}

func (m *SearchItem) GetPopular() int32 {
	if m != nil && m.Popular != nil {
		return *m.Popular
	}
	return 0
}

func (m *SearchItem) GetMagnetURI() string {
	if m != nil && m.MagnetURI != nil {
		return *m.MagnetURI
	}
	return ""
}

type SearchResult struct {
	Result           *int32        `protobuf:"varint,1,req,name=Result" json:"Result,omitempty"`
	ResultSet        []*SearchItem `protobuf:"bytes,2,rep,name=ResultSet" json:"ResultSet,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SearchResult) Reset()                    { *m = SearchResult{} }
func (m *SearchResult) String() string            { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()               {}
func (*SearchResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SearchResult) GetResultSet() []*SearchItem {
	if m != nil {
		return m.ResultSet
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchItem)(nil), "protocol.SearchItem")
	proto.RegisterType((*SearchResult)(nil), "protocol.SearchResult")
}

func init() { proto.RegisterFile("searchdata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8f, 0xcf, 0x4e, 0x84, 0x40,
	0x0c, 0xc6, 0xb3, 0x7f, 0xd8, 0x85, 0xee, 0xaa, 0xeb, 0xa8, 0x49, 0x8f, 0x66, 0x2f, 0x72, 0xe2,
	0xe0, 0x2b, 0x60, 0x34, 0x1c, 0x34, 0x86, 0xd1, 0x07, 0x98, 0x40, 0xa3, 0x24, 0x03, 0x25, 0x50,
	0x62, 0xe2, 0x03, 0xf9, 0x9c, 0x42, 0x89, 0x71, 0x4f, 0x33, 0xfd, 0xf5, 0x97, 0xf4, 0xfb, 0xe0,
	0xd0, 0x93, 0xeb, 0x8a, 0xcf, 0xd2, 0x89, 0x4b, 0xda, 0x8e, 0x85, 0x4d, 0xa8, 0x4f, 0xc1, 0xfe,
	0xf8, 0xb3, 0x00, 0xb0, 0xba, 0xce, 0x84, 0x6a, 0xb3, 0x87, 0xf5, 0x8b, 0xab, 0x09, 0x17, 0xb7,
	0xcb, 0x38, 0x32, 0x37, 0x70, 0xf6, 0xc0, 0x5f, 0x8d, 0x67, 0x57, 0xbe, 0x55, 0x35, 0xf5, 0xb8,
	0x1c, 0x71, 0x70, 0x8a, 0x6d, 0x4b, 0x54, 0xe2, 0x4a, 0xed, 0x2b, 0xd8, 0xa5, 0xec, 0x3d, 0x15,
	0x32, 0xc9, 0xb8, 0x56, 0x78, 0x80, 0xf0, 0xb1, 0xf2, 0x64, 0xab, 0x6f, 0xc2, 0x40, 0xc9, 0x25,
	0x44, 0x13, 0x49, 0x79, 0x68, 0x04, 0x37, 0x8a, 0x2e, 0x60, 0xfb, 0xca, 0xed, 0xe0, 0x5d, 0x87,
	0x5b, 0xbd, 0x30, 0x3a, 0xcf, 0xee, 0xa3, 0x21, 0x79, 0xcf, 0x33, 0x0c, 0x27, 0xe7, 0xf8, 0x04,
	0xfb, 0x39, 0x67, 0x4e, 0xfd, 0xe0, 0xc5, 0x9c, 0xc3, 0x66, 0xfe, 0x69, 0xd6, 0xc0, 0xdc, 0x41,
	0x34, 0xcf, 0x96, 0x64, 0xcc, 0xb9, 0x8a, 0x77, 0xf7, 0xd7, 0xc9, 0x5f, 0xcd, 0xe4, 0xbf, 0xe2,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xdc, 0xef, 0xcf, 0x0e, 0x01, 0x00, 0x00,
}
